site_name: Pilot Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Home: index.md
  - First Steps:
    - Overview: firststeps/index.md
    - Get started: firststeps/getstarted.md
  - Computing:
    - Overview: computing/index.md
    - Connecting: computing/connecting.md
    - Moving data: storage/moving/scp-rsync.md
    - Module environment: computing/modules.md
    - Hardware:
      - CPU nodes: computing/systems/lumic.md
      - Data analytics nodes: computing/systems/lumid.md
      - GPU EAP nodes: computing/systems/kuura.md
    - Running jobs:
      - Slurm Quickstart: computing/jobs/slurm-quickstart.md
      - Available partitions: computing/jobs/partitions.md
      - Batch jobs: computing/jobs/batch-job.md
      - Distribution and binding: computing/jobs/distribution-binding.md
      - High throughput: computing/jobs/throughput.md
      - Interactive usage: computing/jobs/interactive.md
    - Storage:
      - Overview: storage/index.md
      - Lustre: storage/parallel/lustre.md
      - Project Scratch: storage/parallel/lumip.md
      - Project Scratch Fast: storage/parallel/lumif.md
  - Developing:
    - Overview: development/index.md
    - Compiling:
      - Programming environment: development/compiling/prgenv.md
      - Cray compilers: development/compiling/cce.md
      - GNU compilers: development/compiling/gnu.md
      - High performance libraries: development/compiling/libraries.md
      - Using hugepages: development/compiling/hugepages.md
    - Debugging:
      - Debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or dealock: development/debugging/stat-atp.md
    - Performance Analysis:
      - Overview: development/profiling/index.md
      - CrayPat: development/profiling/perftools.md
  - Help Desk: 
    - Help Desk: generic/helpdesk.md
 
theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font: false
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: firststeps/getstarted/
  home_secondary:
    title: LUMI Overview
    page: generic/overview/

#extra_javascript:
#  - 'assets/javascripts/extra.js'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

